name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-latest

    env:
      # Replace with your solution name, i.e. MyWpfApp.sln.
      Solution_Name: MouseTester.sln                            

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
        dotnet-version: 7.x
        # Optional quality of the build. The possible values are: daily, signed, validated, preview, ga.
        #dotnet-quality: 
        # Optional global.json location, if your global.json isn't located in the root of the repo.
        #global-json-file: 
        # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
        #source-url: 
        # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
        #owner: 
        # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
        #config-file: 
        # Optional input to enable caching of the NuGet global-packages folder
        #cache: 
        # Used to specify the path to a dependency file: packages.lock.json. Supports wildcards or a list of file names for caching multiple dependencies.
        #cache-dependency-path: 

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0
      #with:
        # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
        #nuget-version: 
        # NuGet API Key to configure.
        #nuget-api-key: 
        # Source to scope the NuGet API Key to.
        #nuget-api-key-source: 

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
